
["Endoflame Config"]
	#Production of endoflame
	#This is mana each tick, to know how much mana/sec multiply by 20 [3]
	#Range: > 1
	"Endoflame Production" = 3

["Hydroangeas / Thermalily Config"]
	#Hydroangeas duration
	#How many ticks should hydroangeas last [72000]
	#Put a value equal or below 0 to disable it
	"Hydroangeas Ticks" = 72000
	#Hydroangeas production
	#How much mana should it produce each tick [1]
	#Range: > 1
	"Hydroangeas Production" = 1
	#Thermalily production
	#How much mana should it produce each tick [20]
	#Range: > 1
	"Thermalily Production" = 20

["Rosa Arcana Config"]
	#Production of rosa arcana (player exp)
	#This is mana for each player exp point [50]
	#Range: > 1
	"Rosa Arcana Production" = 50
	#Production of rosa arcana (exp orb)
	#This is mana for each orb exp point [50]
	#Range: > 1
	"Rosa Arcana Orb Production" = 50

["Munchdew Config"]
	#Production of munchdew (per leaf)
	#This is mana for each eaten leaf [160]
	#Range: > 1
	"Munchdew Production" = 160
	#Range of munchdew (horizontal)
	#The horizontal range of munchdew [8]
	#Range: > 1
	"Munchdew Range" = 8
	#Range of munchdew (vertical)
	#The vertical range of munchdew [16]
	#Range: > 1
	"Munchdew Range Y" = 16

["Entropinnyum Config"]
	#Production of entropinnyum
	#How much mana entropinnyum produces each explosion (also defines max mana) [6500]
	#Range: > 1
	"Entropinnyum Prod" = 6500

["Kekimurus Config"]
	#Production of kekimurus
	#How much mana kekimurus produces each slice [1800]
	#Range: > 1
	"Kekimurus Prod" = 1800

