#SERVER CONFIGURATION
#does the domain glyph have a cooldown burnout?
doDomainBurnout = true
#does the spell efficiency glyph inflict mana exhaustion?
doDiscountBacklash = true
#maximum number of times spell efficiency can appear
#Range: 0 ~ 10
maxDiscount = 5

